TACS-5 - Add event and option models and unit tests
Leanz652/grupo-3-tacs pull request #9
Opened 2023-04-14 01:18 UTC by matiasyogui

Added Event and Option models
Added Unit test for both models

2023-04-14 03:00 UTC, tomasanchez requested changes
# Review

## The Good

- Test. Buenisimo, cubren todos los casos de usos
- Me gusto el `toggleVote` de `Option`

## The Bad

- El no uso de Custom Exceptions. _Note: actualizar Test cases_
- El no uso de interfaces para `Set`/`List`/`Map` segun corresponda

## The Ugly

- Setters y Getters, chequear el [`Project Lombok`](https://www.baeldung.com/intro-to-project-lombok), contamina la lectura del codigo
- Falta de documentacion. Si bien son intuitivos los nombres [`JavaDocs`](https://www.linkedin.com/pulse/code-documentation-java-best-practices-devang-gandhi/), la consigna pide, y estaria bueno mostrar principalmente los `@Throws`  y las validacioens que hace para no estar yendo y viniendo al codigo a ver que hace.

## Optional

No hace falta, pero estaria bueno para mantener una [Clean Architecture](https://betterprogramming.pub/the-clean-architecture-beginners-guide-e4b7058c1165)

- `DomainServices`. Que realicen las _"Business Rules"_. Deberian ser funciones que se interactuen con distintos `Modelos` y requieran ciertas verificaciones.

Eg. 

`vote(event, user, option)` Relaciona justo las 3.

Si bien `Option` tiene una `toggleVote()`, las verificaciones deberian estar en esta funcion AJENA a las entidades, una implementacion:

```py
def vote(event: Event, option: Option, user: User):

    if user not in event.guests:
       raise InvalidVoteException("User is not invited to the event")
    
   if option not in event.options:
       raise InvalidVoteException("Not an option for this event.")
     
    option.toggle_vote(user)
    event.update(option)
```

 **Kotlin** seria lo ideal, que te deja tirar funciones sin tener que crear una clase.

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +public class Event {
Considerar usar [`ProjectLombok`](https://www.baeldung.com/intro-to-project-lombok). Ahorra el boilerplate, lo que te da mas legibilidad

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +    private HashSet<String> listOfGuests;
`HashSet` es una implementacion concreta, usaria la interfaz que creo que era `Set` .
Como con `List` y `ArrayList`.
Si, seguramente sea un `HashSet`, pero deberiamos abstraernos a la interfaz.

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +            throw new RuntimeException("Only the administrator can modify the event");
Seguramente queramos cachear estas excepciones. Usar una excepcion custom.

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +            throw new RuntimeException("Event is closed");
Idem excepcion custom

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +            throw new RuntimeException("User is not in the guest list");
Idem excepcion custom

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +            throw new RuntimeException("Event is closed");
Estaria bueno que sea `private`, cosa que solo esta entidad conozca esto.

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +            throw new RuntimeException("Option already exists");
Vale la pena romper la ejecucion por esto?
Si mal no recuerdo, si a un `Set` le metes algo que ya esta no pasa nada.

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +        validateIfEventIsOpen();
Cualquiera puede agregar una opcion?

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +            throw new RuntimeException("Option does not exist");
Custom exception

2023-04-14 03:00 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +                .orElseThrow(NoSuchElementException::new);
Esta exception deberia ser la misma de abajo, una custom como por ej `NoOptionVotedException`

2023-04-14 20:28 UTC, matiasyogui commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +public class Event {
Lo agregue, pero en algunas variables (id del user, listOfGuests, etc) no me reconocia el getter

2023-04-14 20:29 UTC, matiasyogui commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +            throw new RuntimeException("Option already exists");
Es verdad, creo que empezo siendo un List y despues lo cambie a Set pero me olvide de sacar la excepcion

2023-04-14 20:31 UTC, matiasyogui commented on rest/src/main/java/com/grupo3/meetings/domain/Event.java
> +        validateIfEventIsOpen();
Aca lo pense como si un usuario pueda proponer una opcion que este fuera de las propuestas por el que creo el Evento, pero es verdad que seria medio confuso, lo cambio

2023-04-15 02:21 UTC, FlorTorreg commented on rest/src/main/java/com/grupo3/meetings/domain/User.java
No faltaria el password de los users? Vamos a usar name para la sesion? Yo estaba pensando que podiamos usar el email. 
Asi lo resolvi yo en kotlin:
data class User (val id: UserId, val email: String, val password: String);

2023-04-15 03:29 UTC, tomasanchez commented on rest/src/main/java/com/grupo3/meetings/domain/User.java
Yo no pondria las password a menos que tengas el `Bcrypt` para el _encoding_.
Si en tu story tenes ya el hash ahi si pondria la password.

2023-04-15 03:30 UTC, FlorTorreg commented on rest/src/main/java/com/grupo3/meetings/domain/User.java
sisi ya tengo el hash

2023-04-15 14:53 UTC, tomasanchez approved these changes

2023-04-15 14:53 UTC, merged